version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202111-02 # https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Configure Environment
          command: |
            BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%S%z")
            echo "export BUILD_DATE=$BUILD_DATE" >> $BASH_ENV
      - run:
          name: Show Configuration
          command: |
            make show-configuration
      - run:
          name: Run Test Suite
          command: |
            make test
