version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.1 # https://circleci.com/developer/images?imageType=machine
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Configure Environment
          command: |
            BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%S%z")
            echo "export BUILD_DATE=$BUILD_DATE" >> $BASH_ENV
      - run:
          name: Show Configuration
          command: |
            make show-configuration
      - run:
          name: Run Functional Test Suite
          command: |
            make test
      - run:
          name: Run Installation Test
          command: |
            curl -L https://raw.githubusercontent.com/makeops-tools/detect-operating-system/main/install.sh | bash
            test -x ~/bin/detect-operating-system
