name: Check Markdown Format
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check-markdown-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          BRANCH_NAME=${{ github.event.repository.default_branch }}
          ./scripts/githooks/markdown-pre-commit.sh
